
# allow configure anubis per chart consumer and also allow renovate to upgrade
anubis:
  image:
    repository: ghcr.io/techarohq/anubis
    tag: v1.23.1@sha256:08b0fbdcd4f56583f734d89abeb27c9d63da59c4d91983651fedb6c2231933a8

